name: "Event Logger"

on:
  release:
  workflow_run:

jobs:
  release_logger:
    # allows for both the workflow_dispatch and push events to trigger this job
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Variables
      run: |
        echo "::notice:: event_name: ${{ github.event_name }}"
        echo "::notice:: event_action: ${{ github.event.action }}"
