name: "Package GitHub release for NPM"
run-name: Package ${{ github.event.inputs.tag }} for NPM Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  Package_NPM_Release:
    name: Package NPM Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: NPM build
        run: |
          npm ci --ignore-scripts
          npm run build

  Publish_NPM_Release:
      name: Publish NPM Release
      needs: Package_NPM_Release

      if: ${{ github.repository == 'homebridge/node-pty-prebuilt-multiarch' }}

      uses: homebridge/.github/.github/workflows/npm-publish.yml@latest
      with:
        install_cmd: npm ci
      secrets:
        npm_auth_token: ${{ secrets.npm_token }}
