name: "PreRun node-gyp MacOS ARM64 Binaries and package for a GitHub Release"
run-name: PreRun node-gyp MacOS ARM64 against ${{ github.event.inputs.tag }} and package for a GitHub Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: macOS - Prebuild Binaries
      if: runner.os == 'macOS'
      run: |
        npm install --ignore-scripts
        env JOBS=max PREBUILD_NODE_GYP=./node_modules/prebuild/node_modules/node-gyp/bin/node-gyp.js node .prebuild/buildify.js

    - name: List
      shell: bash
      run: |
        find .

    - name: Package for GitHub Release
      shell: bash
      run: for i in `ls prebuilds/`; do tar cvzf prebuilds-$i.tar.gz prebuilds/$i; done

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'prebuilds-*tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.event.inputs.tag }}