name: "Remove Release Assets from a GitHub Release"
run-name: Remove Assets from ${{ github.event.inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
      Bundle:
        description: 'Prebuild Bundle'
        required: true
        type: choice
        options:
        - darwin-arm64.tar.gz
        - darwin-x64.tar.gz
        - linux-arm.tar.gz
        - linux-arm64tar.gz
        - linux-ia32.tar.gz
        - linux-x64.tar.gz
        - linuxmusl-arm.tar.gz
        - linuxmusl-arm64.tar.gz
        - linuxmusl-x64.tar.gz
        - win32-ia32.tar.gz
        - win32-x64.tar.gz

jobs:
  Remove:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          assets: node-pty*${{ github.event.inputs.Bundle }}