name: Test
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths-ignore:
      - "**/*.md"
  workflow_dispatch: {} # allow manual triggering just in case
concurrency: ${{ github.workflow }}-${{ github.head_ref }}
env:
  GIT_REF: ${{ github.head_ref || github.ref }}
  GIT_REPO: ${{ github.repository }}
permissions:
  contents: read
jobs:
  prebuild:
    uses: ./.github/workflows/prebuild.yml
    with:
      # Sadly, we cannot use environment variables here
      ref: ${{ github.head_ref || github.ref }}
      repository: ${{ github.repository }}
  test:
    needs: [prebuild]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.GIT_REF }}
          repository: ${{ env.GIT_REPO }}
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          path: prebuilds
          merge-multiple: true
      - run: tree prebuilds
      - run: yarn install --ignore-scripts
      - run: yarn build
      - run: yarn
      - run: yarn test
